name: Build Release
# on:
#   push:
#     tags:
#       - "v*"
on:
  workflow_dispatch:  # 允许手动触发

build:
  runs-on: windows-latest
  steps:
    - name: Checkout code
      uses: actions/checkout@v2  # 检出代码
    - name: Install MinGW
      run: |
        winget install --id 7zip.7zip
        Invoke-WebRequest -Uri "https://github.com/niXman/mingw-builds-binaries/releases/download/14.2.0-rt_v12-rev0/x86_64-14.2.0-release-posix-seh-ucrt-rt_v12-rev0.7z" -OutFile "mingw.7z"
        7z -x mingw.7z -o "C:/mingw"
        set PATH=C:\mingw\bin;%PATH%
    - name: Build
      run: mingw32-make
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: ims.exe
